Display tiles + players + food count + rocks count
lbarreteau/ZAPPY pull request #103
Opened 2023-06-22 10:05 UTC by Rafouzou

### 1. Display all tiles
Open a window, display all the tiles with the correct positioning

### 2. Display all players
For each tile, display the players on this tile (each having the color of their team)

### 3. Display Food count
For each tile, display the amount of food that is on the tile

### 4. Display Rocks count
For each tile, display the total amount of rocks that are on this tile, no matter the type

Closes #100

2023-06-22 11:27 UTC, lbarreteau requested changes

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_active_player_data.cpp
> +        if (!(current_player = findPlayer(m_teams, next_id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_active_player_data.cpp
> +    } else if (!(current_player = findPlayer(m_teams, id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_active_player_data.cpp
> +    } else if (!(player = findPlayer(m_teams, id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_active_player_data.cpp
> +    } else if (!(team = findPlayerTeam(m_teams, player_id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_active_player_data.cpp
> +    } else if ((egg = findEgg(m_teams, egg_id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_general_data.cpp
> +    if (!(team = findTeam(m_teams, team_name))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_map_data.cpp
> +    } else if (!(player = findPlayer(m_teams, player_id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_map_data.cpp
> +    } else if (!(player = findPlayer(m_teams, player_id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_passive_player_data.cpp
> +    if (!(team_by_name = findTeam(m_teams, player_team_name))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_passive_player_data.cpp
> +    if ((team_by_player_id = findPlayerTeam(m_teams, player_id)) && (team_by_name != team_by_player_id)) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/data_parsing/get_passive_player_data.cpp
> +    if (!(player = findPlayerInTeam(team_by_name, player_id))) {
it is forbidden to compare and add in a variable at the same time

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/game.cpp
> +void Game::updateSize(void)
not explicit => updateScreenSize or something like this

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/game.cpp
> +        team_index += 1;
add the increment to the for

2023-06-22 11:27 UTC, lbarreteau commented on gui/src/game.cpp
> +        player_index += 1;
Same

2023-06-22 13:31 UTC, HugoN1 requested changes

2023-06-22 15:32 UTC, lbarreteau requested changes

2023-06-22 15:32 UTC, lbarreteau commented on gui/Makefile
> +CXXFLAGS	= -Wall -Wextra -Werror -Iincludes -I../includes -Isrc -Isrc/game -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
Please remove -Isrc/game

2023-06-22 15:32 UTC, lbarreteau commented on gui/src/game/game.cpp
> +    for (auto team : m_data->m_teams) {
space between for and variables

2023-06-22 15:32 UTC, lbarreteau commented on gui/src/game/game.cpp
> +        team_index += 1;
team_index += 1 in the for like has previously said

2023-06-22 15:32 UTC, lbarreteau commented on gui/src/game/game.cpp
> +        player_index += 1;
player_index += 1 in the for like has previously said

2023-06-22 15:32 UTC, lbarreteau commented on gui/src/game/game.cpp
> +        float b = 0;
![image](https://github.com/lbarreteau/ZAPPY/assets/91669086/598fe911-8830-46c1-b202-fbae7ab25f81)

declare variable in loop, is very very forbiden

2023-06-22 15:55 UTC, lbarreteau approved these changes

2023-06-22 18:48 UTC, AndreasLETANTER approved these changes

2023-06-22 18:48 UTC, AndreasLETANTER commented on gui/sprites/diamond.png
why double diamond png ?

2023-06-22 19:15 UTC, HugoN1 requested changes

2023-06-23 12:02 UTC, HugoN1 approved these changes

2023-06-23 12:34 UTC, merged