Implement incantation command
lbarreteau/ZAPPY pull request #77
Opened 2023-06-19 17:21 UTC by AndreasLETANTER

### Incantation Command
This command takes no arguments, it is used to let the users level up based on the stones at the ground.

It should send a message to everyone when the incantation start, and send the new level to every user at the end of the incantation.

It should check if the stones and the number of player are enough for starting the incantation at the start and at the end, all the player must be freezed during the incantation.

**The command have a complete error handling.**

_It has been implemented with unit tests_

2023-06-19 18:03 UTC, Rafouzou approved these changes
Ok

2023-06-19 20:40 UTC, HugoN1 requested changes

2023-06-19 20:40 UTC, HugoN1 commented on server/src/map_handling/initialize_map.c
> +    refill_map(server_database);
Is it a part of incantation command ? If not, specify this as a "not planned change" and describe it in your PR comment

2023-06-19 20:40 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/commands_errors/tools/is_incantation_possible.c
> +};
2 times the same 2D array ?

2023-06-19 20:40 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/commands_errors/tools/is_incantation_possible.c
> +};
Already existing in incantation_command.c

2023-06-19 20:40 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/commands_errors/tools/is_incantation_possible.c
> +}
third time I see the same method name...

2023-06-19 20:40 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/commands_errors/tools/is_incantation_possible.c
> +bool is_incantation_possible(client_t *client
another is_incantation_possible method ?

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/commands/look/look_command.c
> +    for (unsigned int i = 0; i < server_database->map->height; i++) {
add it to "not planned changes" in PR description

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/commands/set/set_command.c
> +    server_database->map->tiles[5][5].inventory[FOOD] = 0;
add it too

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/commands/inventory/inventory_command.c
> +    cr_assert_stdout_eq_str(PURPLE "Refilling map...\n" RESET GREEN "Client 4 inventory: [ food 10, linemate 0, deraumere 0, sibur 0, mendiane 0, phiras 0, thystame 0 ]\n" RESET);
not planned changes

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/map_handling/clear_map.c
> +static void redirect_all_std(void)
you know what to do

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/map_handling/get_number_ressources_needed.c
> +static void redirect_all_std(void)
another time

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/map_handling/initialize_map.c
> +static void redirect_all_std(void)
you're close to the end

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/server_handling/check_teams_name_exist.c
> +static void redirect_all_std(void)
still same

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/server_handling/connection/clear_logged_clients.c
> +static void redirect_all_std(void)
again and again

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/server_handling/restore_request_buffer.c
> +static void redirect_all_std(void)
one more effort

2023-06-19 20:40 UTC, HugoN1 commented on server/tests/timeout_handling/get_lowest_requested_time.c
> +Test(get_lowest_requested_time, test1, .init = redirect_all_std)
LAST ONEEEE

2023-06-20 06:55 UTC, HugoN1 approved these changes

2023-06-20 07:20 UTC, merged