Implement all passive display for gui
lbarreteau/ZAPPY pull request #96
Opened 2023-06-21 17:48 UTC by AndreasLETANTER

## The GUI collaborators should take an important look on the pull request, this is all the display of passive message to the GUI

### Passive display GUI
This PR add some of the passive display needed for the gui, it implement them as follow:
`pnw` -> When a user connect
`pbc` -> When a broadcast event is finished
`pic` -> When an incantation start
`pie` -> When an incantation is finished
`pfk` -> When a fork start
`pdr` -> When set event occurs
`pgt` -> When take event occurs
`pdi` -> When a player die
`enw` -> When a fork command reach it's end
`ebo` -> When a user connect

**ebo and pnw are sent at the same time due to the subject telling that every user should have an egg, need to see with the graphic if a `enw` at the initialization of the server for letting the graphic now where are the first eggs (which aren't generated by a player)**

Some of the passive display aren't done:
`pex` -> The server doesn't have eject command for the moment
`edi` -> The server doesn't have eject command for the moment
`smg` -> Doesn't know why the server would send a message to the gui (Surely used as bonus for giving more informations to graphic if needed)
`suc` -> The server doesn't take in account the graphic commands for the moment
`sbp` -> Doesn't know when should i display it and it isn't very clear

2023-06-21 18:18 UTC, Rafouzou approved these changes

2023-06-21 18:26 UTC, lbarreteau approved these changes
✨

2023-06-21 20:08 UTC, HugoN1 requested changes

2023-06-21 20:08 UTC, HugoN1 commented on server/src/server_handling/events_handling/no_teams/handle_no_teams_finished_request.c
>  static unsigned int transfer_client_to_team(client_t *client, teams_t *team
please update Doxygen

2023-06-21 20:08 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/commands/incantation_command.c
> +static void handle_graphic_response(server_database_t *server_database,
why are there several functions without Doxygen in this file ?

2023-06-21 20:08 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/commands_errors/incantation_errors.c
> +static void handle_graphic_response(server_database_t *server_database,
No Doxygen ?

2023-06-21 20:08 UTC, HugoN1 commented on server/src/server_handling/events_handling/teams/handle_food_event.c
> +}
a little bit similar to handle_graphic_response() in server/src/server_handling/events_handling/teams/commands_errors/incantation_errors.c

2023-06-21 20:12 UTC, AndreasLETANTER commented on server/src/server_handling/events_handling/teams/handle_food_event.c
> +}
Not the same function print, and use for economizing lines if i set up the buffer to print in arg instead it will have no benefice for doing it

2023-06-22 15:40 UTC, HugoN1 approved these changes

2023-06-22 16:02 UTC, merged