89 create renderer class
lbarreteau/ZAPPY pull request #97
Opened 2023-06-21 19:11 UTC by HugoN1

## Create a Renderer class used to create all the objects to display

### Planed changes :
- Create Renderer class

### Not Planned changes :
- Fix memory handling in Communication class
- Fix Game class constructor

_It has not been implemented with unit tests because Renderer class actually only contains getters and setters_

2023-06-21 19:17 UTC, AndreasLETANTER commented on gui/src/client/ICommunication/Communication.hpp
> +#include "../../team.hpp"
does the -Isrc in the makefile could help you remove the ../ ?

2023-06-21 21:21 UTC, Rafouzou approved these changes

2023-06-22 07:44 UTC, lbarreteau requested changes
Unsigned = non signé

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IGame/Game.cpp
>  std::pair<int, int> Game::getScale() const
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IGame/Game.hpp
> +        std::pair<int, int> getScale() const override;
Unsigned

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IGame/Game.hpp
>          std::pair<int, int> m_scale;
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IGame/IGame.hpp
>          virtual std::pair<int, int> getScale() const = 0;
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IRenderer/IRenderer.hpp
> +        virtual std::pair<int, int> getPos(void) = 0;
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IRenderer/Renderer.cpp
> +std::pair<int, int> Renderer::getPos(void)
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IRenderer/Renderer.hpp
> +        std::pair<int, int> getPos(void) override;
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IRenderer/Renderer.hpp
> +        Renderer(std::string t_textureFileName, std::pair<int, int> t_pos);
Unsigned int

2023-06-22 07:44 UTC, lbarreteau commented on gui/src/game/IRenderer/Renderer.hpp
> +        std::pair<int, int> m_pos;
Unsigned int

2023-06-22 08:04 UTC, lbarreteau approved these changes
Clean 💎

2023-06-22 08:09 UTC, merged